### ISSUE TITLE
knobs for sensitivity analysis does not execute "mrgsim(delta =1.8, end = 24) " command

### ISSUE THREAD

**Issue by safoah** [mrgsolve/gallery#9]
@kylebaron 
Hi everyone,
 I am trying to overlay observed data on a sensitivity analysis using Knobs function from mrgsolve. I keep getting this error message. I think it is because the length of my dataframe is different between the sensitivity analysis output and the observed data

 "Error in xy.coords(x, y) : 'x' and 'y' lengths differ"

code 1

modA <- mrgsim(delta=1.8, end=24)
out <- modA %>% knobs(amt=amt, CL_Scalar=c(0.5,1,1.5,2,3,4),S_SBUP=c(0.1,0.2,0.4,0.6,0.8,1), cmt=cmt) 

plot(out, CP~.) %>%
points(observed_data$Time, observed_data$Obs, col='black')

I have also tried
code 2

out <- modA %>% knobs(amt=amt, CL_Scalar=c(0.5,1,1.5,2,3,4),S_SBUP=c(0.1,0.2,0.4,0.6,0.8,1), cmt=cmt)%>%mrgsim(delta=1.8, end=24)

plot(out, CP~.) %>%
points(observed_data$Time, observed_data$Obs,col='black')

**Comment by kylebaron** [comment]
Hi @safoah  - 

The `plot()` method for `mrgsim()` output is a lattice plot, so you can't add points like this. 

I'm attaching a vignette that will give you ideas for how you can make this overlay with`ggplot2()`. I simulated the "observed" data in the first section; you could use that as an example to work with, but  it isn't really relevant to your specific problem; I just needed something equivalent to your `observed_data` object so I could make the example. 

The vignette is attached in pdf format and I'll punch in the code here too; unfortunately, `reprex()` isn't working today; but will update if I can get a reprex. 

## This shows the worked example

[knobs-ideas.pdf](https://github.com/mrgsolve/gallery/files/8490154/knobs-ideas.pdf)


## This is the code behind the example in the pdf

```r
library(mrgsolve)
library(ggplot2)
library(dplyr)

#' # My model

data <- expand.ev(amt = 100)
mod <- modlib("pk2")

#' # "Observed" data
#' 
#' This is only to have something to illustrate with. We keep the `true`
#' data (as `CP`) as well as data simulated with error `DV` so we can 
#' compare later. 
#' 
set.seed(10102)
data <- mrgsim_df(
  mod, data, end = -1, add = c(0.25, 1, 3, 5, 12, 24), 
  obsonly = TRUE
) %>% mutate(DV = CP * (1+rnorm(n(), 0, 0.1)))

#' We have the data with error and the `true` data
ggplot(data, aes(x = time)) + 
  geom_point(aes(y = CP)) + 
  geom_line(aes(y = DV))

#' # Run knobs
amt <- seq(60, 140, 20)
cmt <- 1
CL <- seq(0.6, 1.4, 0.2)

out <- 
  mod %>% 
  knobs(amt = amt, cmt = cmt, CL = CL, delta = 0.25) %>% 
  as_tibble()

#' # Plot
#' 
#' ## Just the data from `knobs()`
p_sim <- ggplot() + 
  geom_line(data = out, aes(time, CP, colour = factor(amt))) +
  facet_wrap(~CL, ncol = 3) 
  
p_sim

#' ## Now, overlay the observed data ... with error
p_overlay <- 
  p_sim + 
  geom_point(data = data, aes(time, DV))

p_overlay

#' 
#' ## Now, overlay the true observed data
#' 
#' This should be an exact match at `amt = 100` and `CL = 1.0`
#' 
p_match <- 
  p_sim + 
  geom_point(data = data,  aes(time, CP)) 
  
p_match



```

**Comment by safoah** [comment]
Thank you soo much @kylebaron

**Comment by kylebaron** [comment]
No problem; let me know if we can help with anything else.
